export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",

  SET_ORDERS: "SET_ORDERS",
  SELECTED_ORDER: "SELECTED_ORDER",
  REMOVE_SELECTED_ORDER: "REMOVE_SELECTED_ORDER",
};